'\"
'\" Copyright (c) 1998 Sun Microsystems, Inc.
'\"
'\" See the file "license.terms" for information on usage and redistribution
'\" of this file, and for a DISCLAIMER OF ALL WARRANTIES.
'\" 
'\" RCS: @(#) $Id: EventDeleter.3,v 1.1 1998/10/14 21:09:08 cvsadmin Exp $
'\" 
.so man.macros
.TH EventDeleter 3 1.0 Jacl "Jacl Library Procedures"
.BS
.SH INTERFACE
tcl.lang.EventDeleter -- Interface for deleting events from the
Notifier's event queue.

.SH METHODS
.sp
int \fBdeleteEvent\fR(TclEvent \fIevent\fR)

.SH ARGUMENTS
.AS TclObject "table[]" .
.AP TclEvent event
Check whether this event should be deleted from the event queue.
.BE

.SH DESCRIPTION

The EventDeleter interface is used for specifying which event should
be deleted from the event queue.  When \fBdeleteEvents\fR is called on
a Notifier instance, it will invoke the \fBdeleteEvent\fR method of
the EventDeleter argument passed to it, once for each event in the
event queue. \fBdeleteEvent\fR returns 1 for all events that should be
deleted and 0 for events that should remain in the queue.  If
\fBdeleteEvent\fR determines that an event should be removed, it
should perform appropriate clean up on the event instance.

.SH "EQUIVALENT C FUNCTIONS"
Tcl_EventDeleteProc

.SH "SEE ALSO"
TclEvent, Notifier

.SH KEYWORDS
event, notifier, event queue
