'\"
'\" Copyright (c) 1996-1998 Sun Microsystems, Inc.
'\"
'\" See the file "license.terms" for information on usage and redistribution
'\" of this file, and for a DISCLAIMER OF ALL WARRANTIES.
'\" 
'\" RCS: @(#) $Id: InternalRep.3,v 1.1 1998/10/14 21:09:09 cvsadmin Exp $
'\" 
.so man.macros
.TH "InternalRep" 3 1.0 Jacl "Jacl Library Procedures"
.BS
.SH CLASS
tcl.lang.InternalRep -- This class is an abstract base class of all
the internal representation types in Tcl.

.SH METHODS
.sp
void \fBdispose\fR()
.sp
InternalRep \fBduplicate\fR()
.sp
String \fBtoString\fR()

.BE
.SH DESCRIPTION
.PP
The \fBInternalRep\fR class is an abstract base class of all the
internal representation types in Tcl.  All InternalRep subclasses must
implement the following three methods.
.TP
\fBdispose\fR
The \fBdispose\fR method is called when an InternalRep is no longer
used by Tcl. It should free all the resources used by this InternalRep
instance.
.TP
\fBduplicate\fR
The \fBduplicate\fR method is called when an exact copy of the
InternalRep is needed during a copy-on-write operation.
.TP
\fBtoString\fR
The \fBtoString\fR method is called when a string representation is
needed for a TclObject.
.SH "EQUIVALENT C FUNCTIONS"
Tcl_ObjType.freeProc, Tcl_ObjType.dupIntRepProc, Tcl_ObjType.updateStringProc
.SH "SEE ALSO"
TclObject, TclList, TclIndex, TclDouble, TclString, TclInteger, TclBoolean, ReflectObject
.SH KEYWORDS
internal representation, object, object type, abstract class
