'\"
'\" Copyright (c) 1996-1998 Sun Microsystems, Inc.
'\"
'\" See the file "license.terms" for information on usage and redistribution
'\" of this file, and for a DISCLAIMER OF ALL WARRANTIES.
'\" 
'\" RCS: @(#) $Id: TclString.3,v 1.1 1998/10/14 21:09:09 cvsadmin Exp $
'\" 
.so man.macros
.TH TclString 3 1.0 Jacl "Jacl Library Procedures"
.BS
.SH CLASS
tcl.lang.TclString -- This class is used to create and modify Tcl string
objects. 

.SH EXTENDS
tcl.lang.InternalRep

.SH METHODS
.sp
static TclObject \fBnewInstance\fR(String \fIstrValue\fR)
.sp
static void \fBappend\fR(TclObject \fItobj\fR, String \fIstring\fR)

.SH ARGUMENTS
.AS TclObject "strValue" .
.AP TclObject tobj
TclObject to append a string to.  If the internal representation of
\fItobj\fR is not TclString, the method converts it to TclString.
.AP String strValue
Value of internal string in newly created TclObject.
.AP String string
String to append to the end of the string in the internal
representation of \fItobj\fR.
.BE

.SH DESCRIPTION
.TP
\fBnewInstance\fR
The \fBnewInstance\fR method creates and returns a new TclString whose internal
representation contains the string \fIstrValue\fR.
.TP
\fBappend\fR
The \fBappend\fR method concatenates \fIstring\fR to the end of the String
internally to \fItobj\fR.

.SH "EQUIVALENT C FUNCTIONS"
Tcl_NewStringObj, Tcl_AppendToObj

.SH "SEE ALSO"
InternalRep, TclObject, TclList, TclIndex, TclDouble, TclInteger, TclBoolean, ReflectObject

.SH KEYWORDS
internal representation, object, object type, string, append
